/* Generated By:JJTree: Do not edit this line. ASTARGUMENTSLIST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTARGUMENTSLIST extends SimpleNode {
  public ASTARGUMENTSLIST(int id) {
    super(id);
  }

  public ASTARGUMENTSLIST(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a65a2343c4549cfcc7d98abd9a5018fa (do not edit this line) */
