/* Generated By:JJTree: Do not edit this line. ASTBOOL.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBOOL extends SimpleNode {
  public ASTBOOL(int id) {
    super(id);
  }

  public ASTBOOL(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a6f33dfd2d3a1e58de9ba77f3239ab57 (do not edit this line) */
