/* Generated By:JJTree: Do not edit this line. ASTBINOP.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBINOP extends SimpleNode {
  public ASTBINOP(int id) {
    super(id);
  }

  public ASTBINOP(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e82cea814a48fba535a4c1d538cd8ef5 (do not edit this line) */
