/* Generated By:JJTree: Do not edit this line. ASTBOOLEQLS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBOOLEQLS extends SimpleNode {
  public ASTBOOLEQLS(int id) {
    super(id);
  }

  public ASTBOOLEQLS(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=46d1c4a8933195271dc9013f51abac0d (do not edit this line) */
