/* Generated By:JJTree: Do not edit this line. ASTCOMPOP.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCOMPOP extends SimpleNode {
  public ASTCOMPOP(int id) {
    super(id);
  }

  public ASTCOMPOP(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ce81a20827bf684492b1c4f1d3d0a257 (do not edit this line) */
