/* Generated By:JJTree: Do not edit this line. ASTCLOSESTATEMENTBLOCK.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCLOSESTATEMENTBLOCK extends SimpleNode {
  public ASTCLOSESTATEMENTBLOCK(int id) {
    super(id);
  }

  public ASTCLOSESTATEMENTBLOCK(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0e44386005da33ae5931c93b29f60982 (do not edit this line) */
