/* Generated By:JJTree: Do not edit this line. ASTEXPRESSION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEXPRESSION extends SimpleNode {
  public ASTEXPRESSION(int id) {
    super(id);
  }

  public ASTEXPRESSION(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=daef46e97a7a9e1518e559930c7724e3 (do not edit this line) */
