/* Generated By:JJTree: Do not edit this line. ASTFUNCTION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFUNCTION extends SimpleNode {
  public ASTFUNCTION(int id) {
    super(id);
  }

  public ASTFUNCTION(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5e3448f3306b2412065fa30ebfa69b86 (do not edit this line) */
