/* Generated By:JJTree: Do not edit this line. ASTFALSE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFALSE extends SimpleNode {
  public ASTFALSE(int id) {
    super(id);
  }

  public ASTFALSE(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=65d765fc2a5a80dfe67d1e53c0815e10 (do not edit this line) */
