/* Generated By:JJTree: Do not edit this line. ASTGREATERTHAN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGREATERTHAN extends SimpleNode {
  public ASTGREATERTHAN(int id) {
    super(id);
  }

  public ASTGREATERTHAN(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e00f1d2728fed65736e69fa67215fcf2 (do not edit this line) */
