/* Generated By:JJTree: Do not edit this line. ASTGREATERTHANEQLS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGREATERTHANEQLS extends SimpleNode {
  public ASTGREATERTHANEQLS(int id) {
    super(id);
  }

  public ASTGREATERTHANEQLS(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3d9d7193ee8ca2c61d52f2a0f07a5aa6 (do not edit this line) */
