/* Generated By:JJTree: Do not edit this line. ASTINT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTINT extends SimpleNode {
  public ASTINT(int id) {
    super(id);
  }

  public ASTINT(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8778cb5c84a86e089ed8cdd00f18de79 (do not edit this line) */
