/* Generated By:JJTree: Do not edit this line. ASTLESSTHANEQLS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLESSTHANEQLS extends SimpleNode {
  public ASTLESSTHANEQLS(int id) {
    super(id);
  }

  public ASTLESSTHANEQLS(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b217c63de97dbd35975454e3e4e7d70d (do not edit this line) */
