/* Generated By:JJTree: Do not edit this line. ASTLESSTHAN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLESSTHAN extends SimpleNode {
  public ASTLESSTHAN(int id) {
    super(id);
  }

  public ASTLESSTHAN(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=72bfe9cdbcfdc3cdd29269780058e357 (do not edit this line) */
