/* Generated By:JJTree: Do not edit this line. ASTMINUS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMINUS extends SimpleNode {
  public ASTMINUS(int id) {
    super(id);
  }

  public ASTMINUS(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=82dc8965f15dcf8af6602474c9dab122 (do not edit this line) */
