/* Generated By:JJTree: Do not edit this line. ASTNOTEQLS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNOTEQLS extends SimpleNode {
  public ASTNOTEQLS(int id) {
    super(id);
  }

  public ASTNOTEQLS(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=44629aa708861308e3dd234fb5c365d6 (do not edit this line) */
