/* Generated By:JJTree: Do not edit this line. ASTPARAMSLIST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPARAMSLIST extends SimpleNode {
  public ASTPARAMSLIST(int id) {
    super(id);
  }

  public ASTPARAMSLIST(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=11f0a6080a42e876bab4f1448b1c3332 (do not edit this line) */
