/* Generated By:JJTree: Do not edit this line. ASTRCHAIN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRCHAIN extends SimpleNode {
  public ASTRCHAIN(int id) {
    super(id);
  }

  public ASTRCHAIN(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d917050f4e79dec7e0834443c396eadd (do not edit this line) */
