/* Generated By:JJTree: Do not edit this line. ASTSTATEBLOCK.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSTATEBLOCK extends SimpleNode {
  public ASTSTATEBLOCK(int id) {
    super(id);
  }

  public ASTSTATEBLOCK(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=109e825b8630146dfe0163401dd5e398 (do not edit this line) */
