/* Generated By:JJTree: Do not edit this line. ASTSTATEMENT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSTATEMENT extends SimpleNode {
  public ASTSTATEMENT(int id) {
    super(id);
  }

  public ASTSTATEMENT(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f138f13af4d856b353bb8db96b03eacf (do not edit this line) */
