/* Generated By:JJTree: Do not edit this line. ASTTRUE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTRUE extends SimpleNode {
  public ASTTRUE(int id) {
    super(id);
  }

  public ASTTRUE(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a5a6c045ee0f5b690e31ca6349bcae94 (do not edit this line) */
