/* Generated By:JJTree: Do not edit this line. ASTTYPE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTYPE extends SimpleNode {
  public ASTTYPE(int id) {
    super(id);
  }

  public ASTTYPE(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=330bc04dc49aad62d33681f9ac34956d (do not edit this line) */
