/* Generated By:JavaCC: Do not edit this line. MyJJTreeConstants.java Version 5.0 */
public interface MyJJTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTDECLS = 2;
  public int JJTDECL = 3;
  public int JJTVAR = 4;
  public int JJTCONST = 5;
  public int JJTFUNCTION = 6;
  public int JJTTYPE = 7;
  public int JJTPARAMSLIST = 8;
  public int JJTMAIN = 9;
  public int JJTSTATE = 10;
  public int JJTOPENSTATEMENTBLOCK = 11;
  public int JJTCLOSESTATEMENTBLOCK = 12;
  public int JJTELSE = 13;
  public int JJTWHILE = 14;
  public int JJTBINOP = 15;
  public int JJTNUM = 16;
  public int JJTTRUE = 17;
  public int JJTFALSE = 18;
  public int JJTMINUS = 19;
  public int JJTANDOR = 20;
  public int JJTCOMPOP = 21;
  public int JJTARGUMENTSLIST = 22;
  public int JJTID = 23;
  public int JJTIF = 24;
  public int JJTNUMBER = 25;


  public String[] jjtNodeName = {
    "PROGRAM",
    "void",
    "Decls",
    "decl",
    "VAR",
    "CONST",
    "FUNCTION",
    "TYPE",
    "PARAMSLIST",
    "MAIN",
    "STATE",
    "OPENSTATEMENTBLOCK",
    "CLOSESTATEMENTBLOCK",
    "ELSE",
    "WHILE",
    "BINOP",
    "NUM",
    "TRUE",
    "FALSE",
    "MINUS",
    "ANDOR",
    "COMPOP",
    "ARGUMENTSLIST",
    "ID",
    "IF",
    "number",
  };
}
/* JavaCC - OriginalChecksum=caa7014e71f82c0679a1c230a506f87c (do not edit this line) */
