/* Generated By:JavaCC: Do not edit this line. MyJJTreeConstants.java Version 5.0 */
public interface MyJJTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTVAR = 2;
  public int JJTCONST = 3;
  public int JJTFUNCTION = 4;
  public int JJTTYPE = 5;
  public int JJTINT = 6;
  public int JJTBOOL = 7;
  public int JJTPARAMSLIST = 8;
  public int JJTMAIN = 9;
  public int JJTEQUALS = 10;
  public int JJTOPENSTATEMENTBLOCK = 11;
  public int JJTCLOSESTATEMENTBLOCK = 12;
  public int JJTIF = 13;
  public int JJTELSE = 14;
  public int JJTWHILE = 15;
  public int JJTBINOP = 16;
  public int JJTPLUS = 17;
  public int JJTMINUS = 18;
  public int JJTNUM = 19;
  public int JJTTRUE = 20;
  public int JJTFALSE = 21;
  public int JJTANDOR = 22;
  public int JJTCOMPOP = 23;
  public int JJTARGUMENTSLIST = 24;
  public int JJTID = 25;
  public int JJTLCHAIN = 26;
  public int JJTRCHAIN = 27;


  public String[] jjtNodeName = {
    "PROGRAM",
    "void",
    "VAR",
    "CONST",
    "FUNCTION",
    "TYPE",
    "INT",
    "BOOL",
    "PARAMSLIST",
    "MAIN",
    "EQUALS",
    "OPENSTATEMENTBLOCK",
    "CLOSESTATEMENTBLOCK",
    "IF",
    "ELSE",
    "WHILE",
    "BINOP",
    "PLUS",
    "MINUS",
    "NUM",
    "TRUE",
    "FALSE",
    "ANDOR",
    "COMPOP",
    "ARGUMENTSLIST",
    "ID",
    "LCHAIN",
    "RCHAIN",
  };
}
/* JavaCC - OriginalChecksum=1ec160ddbf96591ec77a98466f4bfaef (do not edit this line) */
