/* Generated By:JJTree: Do not edit this line. ASTAdd_op.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAdd_op extends SimpleNode {
  public ASTAdd_op(int id) {
    super(id);
  }

  public ASTAdd_op(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bfc9f0ec3dc4c4628ec7e1111f08febb (do not edit this line) */
