/* Generated By:JJTree: Do not edit this line. ASTBool_val.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBool_val extends SimpleNode {
  public ASTBool_val(int id) {
    super(id);
  }

  public ASTBool_val(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b2b45add91ff5c078a6fa8408c85e53f (do not edit this line) */
