/* Generated By:JJTree: Do not edit this line. ASTFunction_return.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunction_return extends SimpleNode {
  public ASTFunction_return(int id) {
    super(id);
  }

  public ASTFunction_return(MyJJ p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyJJVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=25ce49f6b787b6930821c13c0f182e12 (do not edit this line) */
