/* Generated By:JavaCC: Do not edit this line. MyJJTreeConstants.java Version 5.0 */
public interface MyJJTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTDECL = 2;
  public int JJTVAR_DECL = 3;
  public int JJTCONST_DECL = 4;
  public int JJTASSIGN = 5;
  public int JJTFUNCTION = 6;
  public int JJTSTM = 7;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "Decl",
    "Var_decl",
    "Const_decl",
    "ASSIGN",
    "Function",
    "STM",
  };
}
/* JavaCC - OriginalChecksum=d6f84c422b8e056d68c756b18c40ff0d (do not edit this line) */
