/* Generated By:JavaCC: Do not edit this line. MyJJVisitor.java Version 5.0 */
public interface MyJJVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTDecl node, Object data);
  public Object visit(ASTVar_decl node, Object data);
  public Object visit(ASTConst_decl node, Object data);
  public Object visit(ASTASSIGN node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTSTM node, Object data);
}
/* JavaCC - OriginalChecksum=c8177a983b7f054860a32b758244b3b9 (do not edit this line) */
