/* Generated By:JJTree: Do not edit this line. ASTAnd_Or.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAnd_Or extends SimpleNode {
  public ASTAnd_Or(int id) {
    super(id);
  }

  public ASTAnd_Or(JJTree p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=eb009b88ce851720a17cf2271640e801 (do not edit this line) */
