/* Generated By:JJTree: Do not edit this line. ASTCondition_Statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCondition_Statement extends SimpleNode {
  public ASTCondition_Statement(int id) {
    super(id);
  }

  public ASTCondition_Statement(JJTree p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=73561d11e3c99063dda4e44053e5d12b (do not edit this line) */
