/* Generated By:JJTree: Do not edit this line. ASTconditionPrime.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTconditionPrime extends SimpleNode {
  public ASTconditionPrime(int id) {
    super(id);
  }

  public ASTconditionPrime(JJTree p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1d0a76b715ee07a509e82f841b4e5bf1 (do not edit this line) */
