/* Generated By:JJTree: Do not edit this line. ASTComp_op.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTComp_op extends SimpleNode {
  public ASTComp_op(int id) {
    super(id);
  }

  public ASTComp_op(JJTree p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0067dd82ce2dcfd25af185f86d316b21 (do not edit this line) */
