/* Generated By:JJTree: Do not edit this line. ASTConst_decl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTConst_decl extends SimpleNode {
  public ASTConst_decl(int id) {
    super(id);
  }

  public ASTConst_decl(JJTree p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c711ac92e841db534e0e930b6c8166f7 (do not edit this line) */
