/* Generated By:JJTree: Do not edit this line. ASTfunction_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfunction_list extends SimpleNode {
  public ASTfunction_list(int id) {
    super(id);
  }

  public ASTfunction_list(JJTree p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2c7404e9e8bf51e561cd5eec26c1ab2c (do not edit this line) */
