/* Generated By:JJTree: Do not edit this line. ASTFunction_Return.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunction_Return extends SimpleNode {
  public ASTFunction_Return(int id) {
    super(id);
  }

  public ASTFunction_Return(JJTree p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=16f83a7242e4f0c614e49d923452593d (do not edit this line) */
