/* Generated By:JJTree: Do not edit this line. ASTParams.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTParams extends SimpleNode {
  public ASTParams(int id) {
    super(id);
  }

  public ASTParams(JJTree p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=14ecb1b1976c84b995111b8ff8f9e577 (do not edit this line) */
