/* Generated By:JJTree&JavaCC: Do not edit this line. JJTreeConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JJTreeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int SEMIC = 12;
  /** RegularExpression Id. */
  int COLON = 13;
  /** RegularExpression Id. */
  int ASSIGN = 14;
  /** RegularExpression Id. */
  int LCHAIN = 15;
  /** RegularExpression Id. */
  int RCHAIN = 16;
  /** RegularExpression Id. */
  int LBR = 17;
  /** RegularExpression Id. */
  int RBR = 18;
  /** RegularExpression Id. */
  int PLUS = 19;
  /** RegularExpression Id. */
  int MINUS = 20;
  /** RegularExpression Id. */
  int UNDERSCORE = 21;
  /** RegularExpression Id. */
  int NOTOP = 22;
  /** RegularExpression Id. */
  int OROP = 23;
  /** RegularExpression Id. */
  int ANDOP = 24;
  /** RegularExpression Id. */
  int BOOLEQLS = 25;
  /** RegularExpression Id. */
  int NOTEQLS = 26;
  /** RegularExpression Id. */
  int LESSTHAN = 27;
  /** RegularExpression Id. */
  int GREATERTHAN = 28;
  /** RegularExpression Id. */
  int LESSEQL = 29;
  /** RegularExpression Id. */
  int GREATEQL = 30;
  /** RegularExpression Id. */
  int VARIABLE = 31;
  /** RegularExpression Id. */
  int CONSTANT = 32;
  /** RegularExpression Id. */
  int RETURN = 33;
  /** RegularExpression Id. */
  int INTEGER = 34;
  /** RegularExpression Id. */
  int BOOLEAN = 35;
  /** RegularExpression Id. */
  int VOID = 36;
  /** RegularExpression Id. */
  int MAIN = 37;
  /** RegularExpression Id. */
  int IF = 38;
  /** RegularExpression Id. */
  int ELSE = 39;
  /** RegularExpression Id. */
  int TRUE = 40;
  /** RegularExpression Id. */
  int FALSE = 41;
  /** RegularExpression Id. */
  int WHILE = 42;
  /** RegularExpression Id. */
  int SKIPSKIP = 43;
  /** RegularExpression Id. */
  int NUM = 44;
  /** RegularExpression Id. */
  int DIGIT = 45;
  /** RegularExpression Id. */
  int ID = 46;
  /** RegularExpression Id. */
  int LETTER = 47;
  /** RegularExpression Id. */
  int OTHER = 48;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"/*\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 10>",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"_\"",
    "\"~\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"var\"",
    "\"const\"",
    "\"return\"",
    "\"integer\"",
    "\"boolean\"",
    "\"void\"",
    "\"main\"",
    "\"if\"",
    "\"else\"",
    "\"true\"",
    "\"false\"",
    "\"while\"",
    "\"skip\"",
    "<NUM>",
    "<DIGIT>",
    "<ID>",
    "<LETTER>",
    "<OTHER>",
  };

}
