/* Generated By:JavaCC: Do not edit this line. JJTreeTreeConstants.java Version 5.0 */
public interface JJTreeTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTDECL = 2;
  public int JJTASSIGN = 3;
  public int JJTFUNCTION = 4;
  public int JJTFUNCTION_RETURN = 5;
  public int JJTTYPE = 6;
  public int JJTPARAMS = 7;
  public int JJTMAIN = 8;
  public int JJTBIN_OP = 9;
  public int JJTFRAGMENT = 10;
  public int JJTAND_OR = 11;
  public int JJTCOMP_OP = 12;
  public int JJTARGS = 13;
  public int JJTID = 14;
  public int JJTNUM = 15;
  public int JJTBOOL = 16;
  public int JJTMINUS = 17;
  public int JJTCONDITION_STATEMENT = 18;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "Decl",
    "Assign",
    "Function",
    "Function_Return",
    "Type",
    "Params",
    "Main",
    "Bin_op",
    "Fragment",
    "And_Or",
    "Comp_op",
    "Args",
    "ID",
    "Num",
    "Bool",
    "Minus",
    "Condition_Statement",
  };
}
/* JavaCC - OriginalChecksum=4b00bbca3e0d9a8301c18054a9d7eb66 (do not edit this line) */
