/* Generated By:JavaCC: Do not edit this line. JJTreeVisitor.java Version 5.0 */
public interface JJTreeVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTDecl node, Object data);
  public Object visit(ASTAssign node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTFunction_Return node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTParams node, Object data);
  public Object visit(ASTMain node, Object data);
  public Object visit(ASTBin_op node, Object data);
  public Object visit(ASTFragment node, Object data);
  public Object visit(ASTAnd_Or node, Object data);
  public Object visit(ASTComp_op node, Object data);
  public Object visit(ASTArgs node, Object data);
  public Object visit(ASTID node, Object data);
  public Object visit(ASTNum node, Object data);
  public Object visit(ASTBool node, Object data);
  public Object visit(ASTMinus node, Object data);
  public Object visit(ASTCondition_Statement node, Object data);
}
/* JavaCC - OriginalChecksum=b7bb25fd7a8fcd5f9965cefb41dcad6d (do not edit this line) */
